In [5]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.array([[1,2,3],[4,5,6,]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.linspace(0,10,11) # 3rd argument is the number of points between first and second argument

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.eye(3) # It is a 2D square matrix , identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.rand(3) # return 3 random nos between 0 and 1

array([0.37718255, 0.75880487, 0.29871826])

In [130]:
np.random.randn(3,3) # returns 3,3 2d array of random elements

array([[ 1.31491137, -0.51505727,  1.25451466],
       [-1.35814325,  1.21819146, -2.27316744],
       [-2.03324967, -1.0099042 , -0.11391726]])

In [128]:
np.random.randint(1,100) # Random item between 1 and 100 excluding 100

74

In [40]:
np.random.randint(1,100,10) # 10 random numbers between 1 and 100

array([32, 31, 78, 52, 27, 31, 62, 74, 44, 69])

In [42]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [46]:
arr.max()
arr.argmax()

2

In [48]:
type(arr)

numpy.ndarray

In [78]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
arr_2d[0]

array([1, 2, 3])

In [82]:
arr_2d[0][2]

3

In [79]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1][2] # Indexing

In [86]:
arr_2d[1,2]

6

In [88]:
arr_2d[:2,1:] # including all rows till 2 and all cols from 1 till end
# left is inclusive and right is exclusive

array([[2, 3],
       [5, 6]])

In [90]:
arr_2d[1:,1:] # Slicing

array([[5, 6],
       [8, 9]])

In [93]:
arr_2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [95]:
arr_2d[arr>5] 

array([], shape=(0, 3), dtype=int64)

In [98]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
bool_arr=arr>5 # returns a boolean array
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [102]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr>5] # conditional selection

array([ 6,  7,  8,  9, 10])

In [105]:
arr[arr<3]

array([1, 2])

In [140]:
arr_next=np.arange(50).reshape(5,10)
arr_next

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [142]:
arr_next[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [143]:
arr_next[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [147]:
np.random.randint(0,10,5) # returns a numpy array of 5 random integers between 0 and 10

array([6, 2, 7, 1, 2])

In [154]:
np.random.rand(5) # returns a numpy array of 5 numbers between 0 and 1

array([0.43130941, 0.64138575, 0.03051006, 0.86016484, 0.57352566])

In [159]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [165]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])