In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv('Data.csv')

In [136]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [137]:
data_copy=dataset.copy()

In [138]:
data_copy

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Adding dummy columns

In [139]:
dummies = []
cols = ['Country']
for col in cols:
    dummies.append(pd.get_dummies(data_copy[col]))
country_dummies = pd.concat(dummies, axis=1) # making a dummy dataframe
data_copy = pd.concat((country_dummies,data_copy),axis=1)

In [29]:
del data_copy["Country"]

In [142]:
data_copy

France  Germany  Spain  Country   Age   Salary Purchased
0       1        0      0   France  44.0  72000.0        No
1       0        0      1    Spain  27.0  48000.0       Yes
2       0        1      0  Germany  30.0  54000.0        No
3       0        0      1    Spain  38.0  61000.0        No
4       0        1      0  Germany  40.0      NaN       Yes
5       1        0      0   France  35.0  58000.0       Yes
6       0        0      1    Spain   NaN  52000.0        No
7       1        0      0   France  48.0  79000.0       Yes
8       0        1      0  Germany  50.0  83000.0        No
9       1        0      0   France  37.0  67000.0       Yes

In [60]:
X=data_copy.values
Y=data_copy["Purchased"]
X.shape

(10, 6)

In [61]:
X=np.delete(X,5,axis=1)

In [62]:
X

array([[1, 0, 0, 44.0, 72000.0],
       [0, 0, 1, 27.0, 48000.0],
       [0, 1, 0, 30.0, 54000.0],
       [0, 0, 1, 38.0, 61000.0],
       [0, 1, 0, 40.0, 63777.77777777778],
       [1, 0, 0, 35.0, 58000.0],
       [0, 0, 1, 27.0, 52000.0],
       [1, 0, 0, 48.0, 79000.0],
       [0, 1, 0, 50.0, 83000.0],
       [1, 0, 0, 37.0, 67000.0]], dtype=object)

### FILL THE MISSING NaN values

In [143]:
data_copy.Salary.fillna(data_copy.Salary.mean(),inplace=True)
data_copy.Age.fillna(data_copy.Age.mode()[0],inplace=True)

### Scaling the Features

In [144]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=scaler.fit_transform(X)

In [145]:
X

array([[1.        , 0.        , 0.        , 0.73913043, 0.68571429],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.13043478, 0.17142857],
       [0.        , 0.        , 1.        , 0.47826087, 0.37142857],
       [0.        , 1.        , 0.        , 0.56521739, 0.45079365],
       [1.        , 0.        , 0.        , 0.34782609, 0.28571429],
       [0.        , 0.        , 1.        , 0.        , 0.11428571],
       [1.        , 0.        , 0.        , 0.91304348, 0.88571429],
       [0.        , 1.        , 0.        , 1.        , 1.        ],
       [1.        , 0.        , 0.        , 0.43478261, 0.54285714]])

In [146]:
from sklearn.model_selection import train_test_split

In [89]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [112]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

### Using Logistic Regression

In [113]:
algo=LogisticRegression()
algo.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [114]:
print(algo.score(x_train,y_train))
print(algo.score(x_test,y_test))

0.75
0.5


### Using KNN

In [149]:
algo=KNeighborsClassifier(n_neighbors=4)
algo.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [150]:
print(algo.score(x_train,y_train))
print(algo.score(x_test,y_test))

0.75
0.5


### Using DT

In [147]:
algo=DecisionTreeClassifier()
algo.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [148]:
print(algo.score(x_train,y_train))
print(algo.score(x_test,y_test))

1.0
0.5


### Analysis of predicted model

In [120]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [121]:
confusion_matrix(y_test,algo.predict(x_test))

array([[1, 0],
       [1, 0]])

In [122]:
print(classification_report(y_test,algo.predict(x_test)))

             precision    recall  f1-score   support

         No       0.50      1.00      0.67         1
        Yes       0.00      0.00      0.00         1

avg / total       0.25      0.50      0.33         2



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Rough Work

In [127]:
string="abcbc"
a=[]
a.append(pd.get_dummies(dataset["Country"]))
a

[   France  Germany  Spain
 0       1        0      0
 1       0        0      1
 2       0        1      0
 3       0        0      1
 4       0        1      0
 5       1        0      0
 6       0        0      1
 7       1        0      0
 8       0        1      0
 9       1        0      0]

In [140]:
dummy_countries=pd.concat(a,axis=1) # For changing list into dataframe 

In [141]:
dummy_countries

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [132]:
data_copy2=dataset.copy()

In [134]:
data_copy2=pd.concat((data_copy2,country_dummies),axis=1)

In [135]:
data_copy2

Country   Age   Salary Purchased  France  Germany  Spain
0   France  44.0  72000.0        No       1        0      0
1    Spain  27.0  48000.0       Yes       0        0      1
2  Germany  30.0  54000.0        No       0        1      0
3    Spain  38.0  61000.0        No       0        0      1
4  Germany  40.0      NaN       Yes       0        1      0
5   France  35.0  58000.0       Yes       1        0      0
6    Spain   NaN  52000.0        No       0        0      1
7   France  48.0  79000.0       Yes       1        0      0
8  Germany  50.0  83000.0        No       0        1      0
9   France  37.0  67000.0       Yes       1        0      0