In [1]:
import cifar10
import matplotlib.pyplot as plt

## IMPORTING DATASET

In [2]:
cifar10.data_path = "data/CIFAR-10/"

In [3]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [4]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [5]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


## ANALYSING DATA

In [6]:
print(images_train.shape)
images_train[5][20][20]
# It represents RGB value of pixel(20,20) for the 5th image 

(50000, 32, 32, 3)


array([0.47058824, 0.17254902, 0.17647059])

In [7]:
images_train[331][31][8][0] # This is the R value in the RGB code

0.2235294117647059

# Flattening that Data

In [8]:
images_train.shape

(50000, 32, 32, 3)

In [9]:
images_test.shape

(10000, 32, 32, 3)

In [10]:
x_train=images_train.reshape(images_train.shape[0],-1)
x_test=images_test.reshape(images_test.shape[0],-1)

In [11]:
x_train.shape

(50000, 3072)

In [12]:
x_test.shape

(10000, 3072)

In [13]:
y_train=cls_train
y_test=cls_test

In [14]:
labels_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

# Plotting Images

In [ ]:
# Plotting the first 64 images
fig=plt.figure(figsize=(8,8))
for i in range(64):
    ax = fig.add_subplot(8,8,i+1)
    ax.imshow(images_train[i])

## Applying PCA

In [15]:
from sklearn.decomposition import PCA

In [16]:
pca=PCA()
pca.fit_transform(x_train)

array([[-6.40101763e+00,  2.72903876e+00,  1.50171052e+00, ...,
        -7.62287826e-04, -1.16359323e-03, -3.49768400e-04],
       [ 8.29783385e-01, -9.49943219e-01,  6.00375260e+00, ...,
         1.08434589e-04,  5.76715387e-04, -7.71005927e-04],
       [ 7.73019978e+00, -1.15221023e+01, -2.75362051e+00, ...,
        -1.04460109e-03, -2.14105740e-04, -3.93469526e-04],
       ...,
       [ 7.07346587e-01, -1.13425212e+01, -3.93914878e-01, ...,
        -3.80341568e-04,  1.86432348e-03,  1.44785229e-03],
       [ 1.13679090e+01, -3.37597765e+00,  5.56619766e+00, ...,
        -4.67096832e-04,  7.44972963e-04, -1.67065056e-03],
       [ 4.19279645e+00, -1.18418848e+00, -4.44596297e+00, ...,
         9.67968258e-04,  2.40363971e-04, -2.80506224e-05]])

In [21]:
# Calculating optimal k to have 95% (say) variance 
k = 0
total = sum(pca.explained_variance_)
current_sum = 0
while(current_sum / total < 0.999):
    current_sum += pca.explained_variance_[k]
    k += 1
k

1430

#### OPTIMAL K for 99% variance in data will come out to be 658, i.e the number of components to be taken for 99% data : 658

In [22]:
pca=PCA(n_components=k,whiten=True)
x_train_trans=pca.fit_transform(x_train)
x_test_trans=pca.transform(x_test)

## Apply Logisitic Regression Classifier

In [23]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train_trans,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
y_pred=clf.predict(x_test_trans)

In [25]:
clf.score(x_train_trans,y_train)
clf.score(x_test_trans,y_test)
clf.score(x_test_trans,y_test)

0.385

In [26]:
import numpy as np

In [27]:
class_names

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [28]:
result=[]
for i in range(len(y_pred)):
    if y_pred[i]==0:
        result.append(class_names[0])
    elif y_pred[i]==1:
        result.append(class_names[1])
    elif y_pred[i]==2:
        result.append(class_names[2])
    elif y_pred[i]==3:
        result.append(class_names[3])
    elif y_pred[i]==4:
        result.append(class_names[4])
    elif y_pred[i]==5:
        result.append(class_names[5])
    elif y_pred[i]==6:
        result.append(class_names[6])
    elif y_pred[i]==7:
        result.append(class_names[7])
    elif y_pred[i]==8:
        result.append(class_names[8])
    elif y_pred[i]==9:
        result.append(class_names[9])

In [29]:
np.savetxt('cifar_predictions_y_test',result,fmt="%s")